runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

env_variables:
  OPENAI_API_KEY: "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"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto